apiVersion: v2
name: kitlogin-chart
version: 1.0.0
appVersion: 1.0.0
description: A Helm chart for deploying Kitlogin

dependencies:
  - name: cert-manager
    version: 1.6.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  - name: ingress-nginx
    version: 4.0.13
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.nginx.enabled

maintainers:
  - name: analytickit
    email: analytickit@gmail.com