apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kitlogin-prod
  region: us-east-1

# this is important to specify nodeGroup, without this, it creates fargate without any pods to deply the app and you'll get follwing 
# error 0/2 nodes are available: 2 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
nodeGroups:
  - name: ng-kitlogin
    instanceType: t2.medium
    desiredCapacity: 1

availabilityZones: ['us-east-1a','us-east-1b','us-east-1c','us-east-1d']
  
fargateProfiles:
  - name: fg-login
    selectors:
      # All workloads in the "kitlogin" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kitlogin
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:      

    
