# Generated by Django 3.1.6 on 2023-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kituser',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kituser',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
